### ISSUE TITLE
Errors instead of compiled CSS...

### ISSUE THREAD

**Issue by markcastle** [the-jake-group/wp-less-compiler#3]
Hello there,

Installed your plugin on Wordpress 4.1.1 in order to compile style.less created by https://github.com/ptbello/_strap (https://github.com/ptbello/_strap/blob/master/style.less)

Unfortunately upon attempting the compile the .css file it generated a small number of .less-error-message selectors instead eg.

`.less-error-message ul, .less-error-message li {
list-style-type: none;
margin-right: 15px;
padding: 4px 0;
margin: 0;
}`

Regards
Mark

**Comment by markcastle** [comment]
Ooops just noticed that https://github.com/ptbello/_strap/blob/master/style.less is just loads of @import statements which your plugin likely isn't designed to deal with. Sorry about that if so.

**Comment by tybruffy** [comment]
Actually the plugin should support the @import command.  I haven't tested it with 4.1.1.  Is there anyway you can roll back to an older version of WordPress and test it with the same .less files?  It's been a while since I have tested with an updated version of Wordpress, so you may have to roll back to something like 3.8 or 3.9.  If it doesn't work on 3.8 then it's probably some other issue that it doesn't like in the .less files, but I'll have to investigate further to see what it is.

**Comment by markcastle** [comment]
Sure I'll try it later on as soon as I get a chance.  Thank you very much for replying :-)

**Comment by markcastle** [comment]
Sir, your plugin is awesome and I'm an idiot: My web server wasn't serving up .less MIME types.  Now that I've added .less text/css MIME types your plugin works perfectly.  Thank you and sorry for taking up some of your time.

**Comment by tybruffy** [comment]
Glad you were able to get things sorted out!
